/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as _authenticatedRouteImport } from './routes/__authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as _authenticatedTodosRouteImport } from './routes/__authenticated/todos'
import { Route as _authenticatedDashboardRouteImport } from './routes/__authenticated/dashboard'
import { Route as _authenticatedOrganizationPathRouteImport } from './routes/__authenticated/organization/$path'
import { Route as _authenticatedAccountPathRouteImport } from './routes/__authenticated/account/$path'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedRoute = _authenticatedRouteImport.update({
  id: '/__authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/auth/verify-email',
  path: '/auth/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const _authenticatedTodosRoute = _authenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedDashboardRoute = _authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => _authenticatedRoute,
} as any)
const _authenticatedOrganizationPathRoute =
  _authenticatedOrganizationPathRouteImport.update({
    id: '/organization/$path',
    path: '/organization/$path',
    getParentRoute: () => _authenticatedRoute,
  } as any)
const _authenticatedAccountPathRoute =
  _authenticatedAccountPathRouteImport.update({
    id: '/account/$path',
    path: '/account/$path',
    getParentRoute: () => _authenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/success': typeof SuccessRoute
  '/dashboard': typeof _authenticatedDashboardRoute
  '/todos': typeof _authenticatedTodosRoute
  '/auth/$path': typeof AuthPathRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/account/$path': typeof _authenticatedAccountPathRoute
  '/organization/$path': typeof _authenticatedOrganizationPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/success': typeof SuccessRoute
  '/dashboard': typeof _authenticatedDashboardRoute
  '/todos': typeof _authenticatedTodosRoute
  '/auth/$path': typeof AuthPathRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/account/$path': typeof _authenticatedAccountPathRoute
  '/organization/$path': typeof _authenticatedOrganizationPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/__authenticated': typeof _authenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/success': typeof SuccessRoute
  '/__authenticated/dashboard': typeof _authenticatedDashboardRoute
  '/__authenticated/todos': typeof _authenticatedTodosRoute
  '/auth/$path': typeof AuthPathRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/__authenticated/account/$path': typeof _authenticatedAccountPathRoute
  '/__authenticated/organization/$path': typeof _authenticatedOrganizationPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/success'
    | '/dashboard'
    | '/todos'
    | '/auth/$path'
    | '/auth/verify-email'
    | '/account/$path'
    | '/organization/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/success'
    | '/dashboard'
    | '/todos'
    | '/auth/$path'
    | '/auth/verify-email'
    | '/account/$path'
    | '/organization/$path'
  id:
    | '__root__'
    | '/'
    | '/__authenticated'
    | '/accept-invitation'
    | '/success'
    | '/__authenticated/dashboard'
    | '/__authenticated/todos'
    | '/auth/$path'
    | '/auth/verify-email'
    | '/__authenticated/account/$path'
    | '/__authenticated/organization/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  _authenticatedRoute: typeof _authenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  SuccessRoute: typeof SuccessRoute
  AuthPathRoute: typeof AuthPathRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated': {
      id: '/__authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof _authenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/auth/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__authenticated/todos': {
      id: '/__authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof _authenticatedTodosRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/dashboard': {
      id: '/__authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof _authenticatedDashboardRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/organization/$path': {
      id: '/__authenticated/organization/$path'
      path: '/organization/$path'
      fullPath: '/organization/$path'
      preLoaderRoute: typeof _authenticatedOrganizationPathRouteImport
      parentRoute: typeof _authenticatedRoute
    }
    '/__authenticated/account/$path': {
      id: '/__authenticated/account/$path'
      path: '/account/$path'
      fullPath: '/account/$path'
      preLoaderRoute: typeof _authenticatedAccountPathRouteImport
      parentRoute: typeof _authenticatedRoute
    }
  }
}

interface _authenticatedRouteChildren {
  _authenticatedDashboardRoute: typeof _authenticatedDashboardRoute
  _authenticatedTodosRoute: typeof _authenticatedTodosRoute
  _authenticatedAccountPathRoute: typeof _authenticatedAccountPathRoute
  _authenticatedOrganizationPathRoute: typeof _authenticatedOrganizationPathRoute
}

const _authenticatedRouteChildren: _authenticatedRouteChildren = {
  _authenticatedDashboardRoute: _authenticatedDashboardRoute,
  _authenticatedTodosRoute: _authenticatedTodosRoute,
  _authenticatedAccountPathRoute: _authenticatedAccountPathRoute,
  _authenticatedOrganizationPathRoute: _authenticatedOrganizationPathRoute,
}

const _authenticatedRouteWithChildren = _authenticatedRoute._addFileChildren(
  _authenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  _authenticatedRoute: _authenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  SuccessRoute: SuccessRoute,
  AuthPathRoute: AuthPathRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
